import Image from "next/image";
import Link from "next/link";
import { SiteHeader } from "@/src/components/SiteHeader";
import { SiteFooter } from "@/src/components/SiteFooter";
import { caseStudies, creativeImages } from "@/src/data/media";

export default function Home(){return <><SiteHeader/><main>
  <section className="hero"><div className="hero-copy"><p className="kicker"><span/> Performance marketing / Social media</p><h1>Creative<br/><em>meets data.</em></h1><p className="lead">Qamar Abbas builds social campaigns, creative systems and e-commerce growth strategies backed by measurable performance.</p><div className="hero-actions"><Link className="button red" href="/work">View case studies <span>-&gt;</span></Link><Link className="text-link" href="/creatives">Explore creatives <span>-&gt;</span></Link></div></div><div className="portrait-stage"><div className="portrait-word" aria-hidden="true">QAMAR</div><div className="portrait-frame"><Image src="/images/qammer/profile/qamar-abbas-founder.jpg" alt="Qamar Abbas" fill priority sizes="(max-width:900px) 100vw,50vw"/></div><div className="portrait-label"><b>Qamar Abbas</b><span>Performance marketer</span></div></div></section>
  <section className="numbers"><p className="section-index">01 / Updated Meta Ads evidence</p><div className="number-grid"><article><strong>1,098</strong><span>Purchases in featured account view</span></article><article><strong>973K</strong><span>Impressions recorded</span></article><article><strong>46</strong><span>Campaigns reported</span></article><article><strong>3.23%</strong><span>All-click CTR shown</span></article></div><p className="source-note">Featured figures are from Updated Meta Data image 20 and are not presented as totals across every account.</p></section>
  <section className="work home-work"><div className="section-head"><div><p className="section-index">02 / Case studies</p><h2>Evidence,<br/><em>organized.</em></h2></div><p>Two focused stories built from the complete paid-social and commerce dashboard sets.</p></div><div className="case-study-grid">{caseStudies.map(item=><Link className="case-study-card" href={`/work/${item.slug}`} key={item.slug}><div><Image src={item.cover} alt={item.title} fill sizes="(max-width:900px) 100vw,50vw"/></div><p>{item.eyebrow} / {item.count} images</p><h3>{item.title}</h3><span>Explore case study -&gt;</span></Link>)}</div></section>
  <section className="creative-preview"><div className="preview-copy"><p className="section-index light">03 / Creative archive</p><h2>25 pieces.<br/><em>One visual system.</em></h2><p>Browse every supplied brand and social creative in a dedicated interactive gallery.</p><Link className="button red" href="/creatives">View all creatives <span>-&gt;</span></Link></div><div className="preview-stack">{creativeImages.slice(0,3).map((image,index)=><div style={{"--i":index}} key={image.src}><Image src={image.src} alt={image.alt} fill sizes="35vw"/></div>)}</div></section>
  <section className="contact"><p className="section-index">04 / Start a conversation</p><h2>Ready for the<br/><em>next result?</em></h2><Link className="button red" href="/contact">Contact Qamar <span>-&gt;</span></Link></section>
  </main><SiteFooter/></>}
