import Image from "next/image";
import Link from "next/link";
import { SiteHeader } from "@/src/components/SiteHeader";
import { SiteFooter } from "@/src/components/SiteFooter";
import { profile } from "@/src/data/profile";
import { caseStudies, creativeImages } from "@/src/data/media";
import { HomePortrait } from "@/src/components/HomePortrait";
import styles from "./home.module.css";

export const metadata = { title: "Meta Ads & Shopify Growth Specialist", description: "Explore Qamar Abbas's Meta Ads, Shopify growth and social media marketing portfolio, including campaign reporting, e-commerce dashboards and conversion-focused creative." };

const homeHighlights = [
  "4+ years in performance marketing", "Worked with 150+ brands across markets", "Managed $10M+ in ad spend", "Achieved 6x–8x ROAS for e-commerce brands", "Meta Ads & performance marketing specialist", "Creative strategy & creative testing expertise", "Campaign scaling & performance optimization", "Worked with TVM Solutions and Sanborn Marketing", "Founder of a performance marketing agency", "Focused on scalable, profitable e-commerce growth",
];

export default function Home() { return <><SiteHeader /><main>
  <section className={`hero home-hero ${styles.hero}`}><div className="hero-copy"><p className="kicker"><span /> Meta Ads / Shopify / Social Media Marketing</p><h1>E-commerce<br /><em>growth marketing.</em></h1><p className="lead">Qamar Abbas helps e-commerce brands acquire customers and improve conversion through Meta Ads management, Shopify development, social media strategy and performance creative.</p><div className="hero-actions"><Link className="button red" href="/work">View marketing case studies <span aria-hidden="true">→</span></Link><Link className="text-link" href="/creatives">Explore social creatives <span aria-hidden="true">→</span></Link></div><div className="hero-proof" aria-label="Marketing portfolio evidence"><span>20 Meta Ads reports</span><span>20 Shopify dashboards</span><span>25 social creatives</span></div></div><HomePortrait profile={profile} highlights={homeHighlights} /></section>
  <section className="numbers"><p className="section-index">01 / Meta Ads campaign performance</p><div className="number-grid"><article><strong>1,098</strong><span>Purchases in the featured Meta Ads report</span></article><article><strong>973K</strong><span>Paid social impressions recorded</span></article><article><strong>46</strong><span>Meta campaigns analyzed</span></article><article><strong>3.23%</strong><span>All-click CTR in the featured report</span></article></div><p className="source-note">Figures come from one featured Meta Ads account view and are not combined across unrelated stores or reporting periods.</p></section>
  <section className="work home-work"><div className="section-head"><div><p className="section-index">02 / Digital marketing case studies</p><h2>Strategy backed<br /><em>by real data.</em></h2></div><p>Explore verified Meta Ads and Shopify case studies covering paid acquisition, store revenue, traffic, orders and conversion performance.</p></div><div className="case-study-grid">{caseStudies.map(item => <Link className="case-study-card" href={`/work/${item.slug}`} key={item.slug}><div><Image src={item.cover} alt={item.title} fill sizes="(max-width:900px) 100vw,50vw" /></div><p>{item.eyebrow} / {item.count} evidence images</p><h3>{item.title}</h3><span>View full case study&nbsp; →</span></Link>)}</div></section>
  <section className="creative-preview"><div className="preview-copy"><p className="section-index light">03 / Social media creative portfolio</p><h2>Creative built<br /><em>to convert.</em></h2><p>Explore product storytelling, campaign visuals and social-first content designed to earn attention and support e-commerce conversion.</p><Link className="button red" href="/creatives">View creative portfolio <span aria-hidden="true">→</span></Link></div><div className="preview-stack">{creativeImages.slice(0, 3).map((image, index) => <div style={{ "--i": index }} key={image.src}><Image src={image.src} alt={image.alt} fill sizes="35vw" /></div>)}</div></section>
  <section className="contact"><p className="section-index">04 / Grow your e-commerce brand</p><h2>Ready to improve<br /><em>marketing performance?</em></h2><Link className="button red" href="/contact">Discuss your project <span aria-hidden="true">→</span></Link></section>
  </main><SiteFooter /></>; }
